//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIS_Sys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bb_Reg_Curor {
            get {
                return ((int)(this["Bb_Reg_Curor"]));
            }
            set {
                this["Bb_Reg_Curor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("两周")]
        public string Refresh_Date_FW {
            get {
                return ((string)(this["Refresh_Date_FW"]));
            }
            set {
                this["Refresh_Date_FW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("两周")]
        public string Refresh_Date_QC {
            get {
                return ((string)(this["Refresh_Date_QC"]));
            }
            set {
                this["Refresh_Date_QC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DTthumsWidth {
            get {
                return ((int)(this["DTthumsWidth"]));
            }
            set {
                this["DTthumsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DTthumsHeight {
            get {
                return ((int)(this["DTthumsHeight"]));
            }
            set {
                this["DTthumsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("两周")]
        public string Refresh_Date_ZP {
            get {
                return ((string)(this["Refresh_Date_ZP"]));
            }
            set {
                this["Refresh_Date_ZP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int BGthumsWidth {
            get {
                return ((int)(this["BGthumsWidth"]));
            }
            set {
                this["BGthumsWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76")]
        public int BGthumsHeight {
            get {
                return ((int)(this["BGthumsHeight"]));
            }
            set {
                this["BGthumsHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2007Blue")]
        public string SystemUI {
            get {
                return ((string)(this["SystemUI"]));
            }
            set {
                this["SystemUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DTDevice {
            get {
                return ((string)(this["DTDevice"]));
            }
            set {
                this["DTDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BGDevice {
            get {
                return ((string)(this["BGDevice"]));
            }
            set {
                this["BGDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("两周")]
        public string Refresh_Date_BG {
            get {
                return ((string)(this["Refresh_Date_BG"]));
            }
            set {
                this["Refresh_Date_BG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Open_BG_SXT {
            get {
                return ((bool)(this["Open_BG_SXT"]));
            }
            set {
                this["Open_BG_SXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportPrinter {
            get {
                return ((string)(this["ReportPrinter"]));
            }
            set {
                this["ReportPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReportPrintNum {
            get {
                return ((int)(this["ReportPrintNum"]));
            }
            set {
                this["ReportPrintNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string zpBarcodePrinter {
            get {
                return ((string)(this["zpBarcodePrinter"]));
            }
            set {
                this["zpBarcodePrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int zpBarcodePrintNum {
            get {
                return ((int)(this["zpBarcodePrintNum"]));
            }
            set {
                this["zpBarcodePrintNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string djBarcodePrinter {
            get {
                return ((string)(this["djBarcodePrinter"]));
            }
            set {
                this["djBarcodePrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int djBarcodePrintNum {
            get {
                return ((int)(this["djBarcodePrintNum"]));
            }
            set {
                this["djBarcodePrintNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool djBarcodePrint {
            get {
                return ((bool)(this["djBarcodePrint"]));
            }
            set {
                this["djBarcodePrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool zpBarcodePrintSL {
            get {
                return ((bool)(this["zpBarcodePrintSL"]));
            }
            set {
                this["zpBarcodePrintSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string qcListPrinter {
            get {
                return ((string)(this["qcListPrinter"]));
            }
            set {
                this["qcListPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tjBarcodePrinter {
            get {
                return ((string)(this["tjBarcodePrinter"]));
            }
            set {
                this["tjBarcodePrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int tjBarcodePrintNum {
            get {
                return ((int)(this["tjBarcodePrintNum"]));
            }
            set {
                this["tjBarcodePrintNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Open_DT_SXT {
            get {
                return ((bool)(this["Open_DT_SXT"]));
            }
            set {
                this["Open_DT_SXT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Load_DT_IMG {
            get {
                return ((bool)(this["Load_DT_IMG"]));
            }
            set {
                this["Load_DT_IMG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordBBFlag {
            get {
                return ((bool)(this["RecordBBFlag"]));
            }
            set {
                this["RecordBBFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditPicName {
            get {
                return ((bool)(this["EditPicName"]));
            }
            set {
                this["EditPicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DjType {
            get {
                return ((bool)(this["DjType"]));
            }
            set {
                this["DjType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DjNewForm {
            get {
                return ((bool)(this["DjNewForm"]));
            }
            set {
                this["DjNewForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlhCreateFlag {
            get {
                return ((bool)(this["BlhCreateFlag"]));
            }
            set {
                this["BlhCreateFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool zkapp_flag {
            get {
                return ((bool)(this["zkapp_flag"]));
            }
            set {
                this["zkapp_flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool smPhoto_flag {
            get {
                return ((bool)(this["smPhoto_flag"]));
            }
            set {
                this["smPhoto_flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QcBg_flag {
            get {
                return ((bool)(this["QcBg_flag"]));
            }
            set {
                this["QcBg_flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool His_PatInfo_Flag {
            get {
                return ((bool)(this["His_PatInfo_Flag"]));
            }
            set {
                this["His_PatInfo_Flag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Open_Smxj {
            get {
                return ((bool)(this["Open_Smxj"]));
            }
            set {
                this["Open_Smxj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XXX市人民医院")]
        public string Bp_Ksmc {
            get {
                return ((string)(this["Bp_Ksmc"]));
            }
            set {
                this["Bp_Ksmc"] = value;
            }
        }
    }
}
